[package]
name = "last-stanza"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.1"
bevy-inspector-egui = "0.9.0"
bevy_editor_pls = {git = "https://github.com/jakobhellermann/bevy_editor_pls", rev = "6cdec7e"}
# heron = "*"
# bevy-parallax = "*"
# bevy_proto = "*"
# benimator = "*"
# bevy_sprite_animation = {git = "https://github.com/PhaestusFox/bevy_sprite_animation"}

[profile.dev.package."*"]
opt-level = 3