[t.0]
min_spawn_time = 1.0
max_spawn_time = 5.0
hopper = 0
climber = 1
lurker = 0
diver = 0
giant = 0
behemoth = 0

[t.5]
min_spawn_time = 1.0
max_spawn_time = 5.0
hopper = 0
climber = 1
lurker = 0
diver = 0
giant = 0
behemoth = 0

[t.20]
min_spawn_time = 1.0
max_spawn_time = 5.0
hopper = 5
climber = 2
lurker = 0
diver = 0
giant = 1
behemoth = 0

[t.40]
min_spawn_time = 1.0
max_spawn_time = 3.5
hopper = 5
climber = 2
lurker = 1
diver = 0
giant = 1
behemoth = 0
